import { Router } from "express";
import { create, list, get, returnable, addPayment } from "../controllers/orderController.js";
import { requireAuth } from "../middleware/auth.js";
import { requireTenant } from "../middleware/tenant.js";
import { requirePermission } from "../middleware/permissions.js";
import { requireFeature } from "../middleware/planLimits.js";
import { createOnlineOrder, createAdminOnlineOrder, trackOrder, myOrders, adminOnlineList, updateOnlineOrder } from "../controllers/onlineOrderController.js";
import { resolvePublicTenant } from "../middleware/tenant.js";
const r=Router();
r.post("/online", resolvePublicTenant, requireFeature("online_orders"), createOnlineOrder);
r.post("/online/admin", requireAuth, requireTenant, requireFeature("online_orders"), requirePermission("sales.create"), createAdminOnlineOrder);
r.post("/track", resolvePublicTenant, requireFeature("online_orders"), trackOrder);
r.post("/my-orders", resolvePublicTenant, requireFeature("online_orders"), myOrders);
r.get("/online/list", requireAuth, requireTenant, requireFeature("online_orders"), requirePermission("sales.view"), adminOnlineList);
r.patch("/online/:id", requireAuth, requireTenant, requireFeature("online_orders"), requirePermission("sales.create"), updateOnlineOrder);
r.get("/",requireAuth,requireTenant,requirePermission("sales.view"),list);
r.get("/returnable",requireAuth,requireTenant,requirePermission("returns.create"),returnable);
r.get("/:id",requireAuth,requireTenant,requirePermission("sales.view"),get);
r.post("/",requireAuth,requireTenant,requireFeature("pos"),requirePermission("sales.create"),create);
r.post("/:id/payments",requireAuth,requireTenant,requirePermission("sales.create"),addPayment);
export default r;